### ISSUE TITLE
PSG "note off" is missing

### ISSUE THREAD

**Issue by Segaman8** [oerg866/xm2esf#1]
There is no "Note Off's" on PSG channels after using xm2esf.
Feels like theyre just ignored for some reason.
I looked inside *.esf file, and yes, theyre ignored by xm2esf.
Also source code is super old. I was hoped for fixing this issue by myself, but source code, presented here, is of not working beta version.

**Comment by oerg866** [comment]
Hi!Thank you for using xm2esf. I will take a look at this issue later today.If I remember correctly, xm note-offs on PSG channels should be handled  properly but I rarely use them there as it just cuts off the note due to limitations in Echo itself (it does not support release on PSG volume envelopes.)I will check and get back to you.Best wishes,Eric On 22 Sep 2018 04:53, Segaman <notifications@github.com> wrote:There is no "Note Off's" on PSG channels after using xm2esf.
Feels like theyre just ignored for some reason.
I looked inside *.esf file, and yes, theyre ignored by xm2esf.
Also source code is super old. I was hoped for fixing this issue by myself, but source code, presented here, is of not working beta version.

**Comment by oerg866** [comment]
Fixed.
